# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79b8611d9c4e3f66985b133f7e96a4233d7ece22530839f03d636484c8210ea5fd7a5ea8f987be84ba528d7edab7d8c9c51388df4923f36cff8f8814f79e9402

test:
  secret_key_base: f111c078c9132a4d44624eba063a3def800ab17d4dd88d46691418b6d967f9ec534aeccfeee5469c8d5c9f8eba44b12a3e02a9c3d8ea5272f1878e483a91c0e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
